"""create user

Revision ID: 979bb0f2a58a
Revises: f0e39066a190
Create Date: 2018-07-12 14:11:53.470837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979bb0f2a58a'
down_revision = 'f0e39066a190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tweet', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tweet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.drop_column('tweet', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
